---
title: "INLA SPDE approach for Pest data"
author: "J. Francisco Mandujano Reyes"
date: "4/25/2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(INLA)
library(ggplot2)
library(maps)
library(mapdata)
library(plotly)
library(maptools)
library(dplyr)
library(broom)
library(sp)
library(raster)
library(tidyr)
```

```{r, warning = FALSE, message = FALSE}
setwd("/Users/mandujanoreyes/Library/CloudStorage/GoogleDrive-juanipnc6@gmail.com/My Drive/PhD/JunZhu_WNS/Pest_resistance")

# df.pest = read.csv("PotatoClimateIntensityData_OK_resistance_genetics.csv")
# df.pest = read.csv("PotatoClimateIntensityData_OK_resistance_better_genetics_imputed.csv")
# df.pest = read.csv("PotatoClimateIntensityData_OK_resistance_better_genetics_imputed_Jun2.csv")

df.pest1 = read.csv("PotatoClimateIntensityData_OK_resistance_better_genetics_imputed_Jun2_v2.csv")
df.pest2 = read.csv("PotatoClimateIntensityData_OK_resistance_better_genetics_imputed_Jun2_old_gen_v2.csv")

df.pest = cbind(df.pest1, Pco1_old = df.pest2$Pco1, Pco2_old = df.pest2$Pco2, Pco3_old = df.pest2$Pco3) 



```

Select rows with observations for abundance, climate, proportion of potato and genetics (optional).

```{r}
# df.pest = df.pest %>% drop_na(Lon, Lat, Year, Abundance, tmin, tmax, prec, wind, Prop_potato)

# df.pest = df.pest %>% drop_na(Lon, Lat, Year, Abundance, tmin, tmax, prec, wind, Prop_potato, Pco1_imp, Pco2_imp, Pco3_imp)

# df.pest = df.pest %>% drop_na(Lon, Lat, Year, Abundance, tmin, tmax, prec, wind, Prop_potato, Pco1, Pco2, Pco3)

# df.pest = df.pest %>% drop_na(Lon, Lat, Year, Abundance, tmin, tmax, prec, wind, Prop_potato, Prop_dead, N_beetles)

df.pest = df.pest %>% filter(Year >= 2015)

dim(df.pest)
```


```{r}
# df.pest$Prop_dead = sample(df.pest$Prop_dead[!is.na(df.pest$Prop_dead)], dim(df.pest)[1], replace = TRUE)
# df.pest$N_beetles = sample(df.pest$N_beetles[!is.na(df.pest$N_beetles)], dim(df.pest)[1], replace = TRUE)
df.pest$N_dead = as.integer(df.pest$N_beetles*df.pest$Prop_dead)
```

Only after 2015 because we only have three years with resistance data: 2015, 2019, 2023

```{r}
summary(unique(df.pest$field))
```


```{r}
dim(df.pest)
summary(df.pest)
```

```{r}
library(gtsummary)
library(tidyverse)

# df.pest$potato_proportion = as.numeric(df.pest$potato_proportion)
df.pest$wei_prop = as.numeric(df.pest$wei_prop)

# df.pest %>%
#   dplyr::select(N_beetles, Prop_dead, gdd, cum_gdd, tmin_annual, tmax_annual, annual_prcp, summer_tmin, summer_avg, summer_prcp, winter_avg, winter_tmax, potato_proportion, intensity, cpba_count, cpbl_count, Pco1, Pco2, Pco3, lng, lat, year) %>%
#   tbl_summary() %>%
#   as_gt() 

# df.pest$winter_heavy_rainfall_days = 1.0*as.double(df.pest$winter_heavy_rainfall_days) + 0.000000000000001

df.pest$year = as.character(df.pest$year)

df.pest$Pco1_adp = df.pest$Pco1
df.pest$Pco2_adp = df.pest$Pco2
df.pest$Pco3_adp = df.pest$Pco3

df.pest$Pco1 = df.pest$Pco1_old
df.pest$Pco2 = df.pest$Pco2_old
df.pest$Pco3 = df.pest$Pco3_old


df.pest %>%
  dplyr::select(N_beetles, Prop_dead, gdd, cum_gdd, summer_avg_temp, summer_hottest_temp, summer_avg_percip, summer_heavy_rainfall_days, summer_temp_variability, winter_coldest_temp, winter_heavy_rainfall_days, winter_temp_variability, winter_warm_day_count, winter_extreme_cold_days, spring_frost_free_days, wei_prop, wei_intensity, cpba_count, cpbl_count, Pco1, Pco2, Pco3, Pco1_adp, Pco2_adp, Pco3_adp, lng, lat, year) %>%
  tbl_summary() %>%
  as_gt() 




```













```{r}
# create detect outlier function
detect_outlier <- function(x) {
   
  # calculate first quantile
  Quantile1 <- quantile(x, probs=.25)
   
  # calculate third quantile
  Quantile3 <- quantile(x, probs=.75)
   
  # calculate inter quartile range
  IQR = Quantile3 - Quantile1
   
  # return true or false
  x > Quantile3 + (IQR * 1.5) | x < Quantile1 - (IQR * 1.5)
}
 
# create remove outlier function
remove_outlier <- function(dataframe, columns = names(dataframe)) {
   
  # for loop to traverse in columns vector
  for (col in columns) {
     
    # remove observation if it satisfies outlier function
    dataframe <- dataframe[!detect_outlier(dataframe[[col]]), ]
  }
   
  # return dataframe
  # print("Remove outliers")
  return(dataframe)
}
 
# df.pest = remove_outlier(df.pest, c('Abundance', 'tmin', 'tmax', 'prec', 'wind', 'Prop_potato', 'Pco1_imp', 'Pco2_imp', 'Pco3_imp'))

dim(df.pest)
```



```{r}
ggplot(df.pest, aes(x = Lon, y = Lat, color = cpba_count)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Abundance A Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = cpbl_count)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Abundance L Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")


ggplot(df.pest, aes(x = Lon, y = Lat, color = potato_proportion)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Prop potato Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = intensity)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Intensity potato Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")


ggplot(df.pest, aes(x = Lon, y = Lat, color = gdd)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "GDD Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = cum_gdd)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Cummulative GDD Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = tmin)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "T min Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = tmax)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "T max Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = summer_prcp)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Summer Precipitation Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")


ggplot(df.pest, aes(x = Lon, y = Lat, color = Pco1)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "PCo1 Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = Pco2)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "PCo2 Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = Pco3)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "PCo3 Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

ggplot(df.pest, aes(x = Lon, y = Lat, color = Prop_dead)) +
  geom_point(size = 2) +  # Adjust point size
  scale_color_viridis_c() +  # Better color scale for continuous variables
  facet_wrap(~ Year) +  # Wrap by year
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(title = "Prop dead Spatial Distribution Over Time",
       x = "Longitude", y = "Latitude", color = "Value")

```




```{r}
unique(df.pest$Year)
```


```{r, warning = FALSE, message = FALSE}
# extract coordinates
coords = as.data.frame( df.pest[,c(3,4)] ) 

# use correct CRS
map.crs <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
ff = SpatialPoints(coords)
proj4string(ff) <- map.crs

```


```{r,warning = FALSE, message = FALSE}
# get data as data frame object
data = as.data.frame(df.pest)

## in case I want to use a validation set
# # spliting 
# # surv from nov to may, one season
# isel = which(dat$DateColl < "2020-06") # using 15 months for validation 
# #isel = which(dat$DateColl < "2021-06") # check for one year, 15 months, etc... 
# vdat = dat[-isel, ] 
# dat = dat[isel, ] 
# 
# # renaming
# names(dat) = c("DateColl","WNS","species","xcoo","ycoo","country","country2",
#                "y","WA","cell","time","p_indx","envir","canopy","tri","water")
# 
# names(vdat) = c("DateColl","WNS","species","xcoo","ycoo","country","country2",
#                 "y","WA","cell","time","p_indx","envir","canopy","tri","water")

```


```{r,warning = FALSE, message = FALSE}

coords = as.data.frame( data[,c(3,4)] ) 

data$time = data$Year - min(data$Year) + 1 
# data$time = data$year_abd - min(data$year_abd) + 1 

k <- max(unique(data$time)) 

# prmesh1  <- inla.mesh.2d(
#   loc = as.matrix(coords), 
#   max.edge = 0.1, 
#   cutoff = 0.1, # 0.01
#   offset = 0.2)
# 
# tmesh <- inla.mesh.1d(loc = 1:k)
# 
# plot(prmesh1)
# points(coords, pch = 20 )


prmesh1 <- inla.mesh.2d(
  loc = as.matrix(coords), 
  max.edge = 0.07, 
  cutoff = 0.05,
  offset = 0.1)

tmesh <- inla.mesh.1d(loc = 1:k)

plot(prmesh1)
points(coords, pch = 20 )
```

```{r,warning = FALSE, message = FALSE}
prmesh1$n
```

```{r}
# df.pest %>% 
# ggplot(aes(x = Lon, y = Lat, fill = Prop_dead)) +
#   geom_point() +
#   stat_density_2d_filled(aes(z = Prop_dead), geom = "raster", contour = FALSE) +
#   scale_fill_viridis_c() +
#   facet_wrap(~ Year) +
#   labs(title = "Smoothed Predictions Over Time",
#        x = "Longitude", y = "Latitude", fill = "Prediction") +
#   theme_minimal()

node_coords <- prmesh1$loc
distance_matrix <- dist(node_coords)
min_distance <- min(distance_matrix)
max_distance <- max(distance_matrix)

min_distance
max_distance
mean(distance_matrix)

sd(data$Prop_dead, na.rm = T)
```


### A simple example: Standard GLM model

```{r,warning = FALSE, message = FALSE}
# glm data 

# Model formula
## spde model = i for vertices of GMRF
formulae_glm <- N_dead ~ 1 + tmin + tmax + prec + wind + Prop_potato + Abundance + Pco1_imp + Pco2_imp + Pco3_imp 

# Model fitting
res_glm <- inla(formulae_glm,  data = data, # verbose=TRUE,
            # family = "beta",
            family = "binomial",
            Ntrials = data$N_beetles,
            # control.family = list(beta.censor.value = cens, hyper = lkprec),
            control.compute = list(dic = TRUE, waic = TRUE),
            control.predictor = list(compute = TRUE,  
                                     link=1), # logit link
            # control.family = list(hyper = list(prec = prec.prior)), # for normal observations, not used here
            control.fixed = list(expand.factor.strategy = 'inla'))

summary(res_glm)
```

```{r,warning = FALSE, message = FALSE}
# Code for creating a figure with the fixed effects credible intervals

# alpha <- res$marginals.fixed$tri
# quant1 <- inla.qmarginal(0.025, alpha)
# quant2 <- inla.qmarginal(0.975, alpha)
# ggplot(data.frame(inla.smarginal(alpha)), aes(x, y)) +
#   geom_line() +
#   geom_vline(xintercept=inla.emarginal(function(x) x, alpha), size=1, color="red")+
#   geom_area(data = subset(data.frame(inla.smarginal(alpha)),
#                           x < quant1),
#             fill = "black") +
#   geom_area(data = subset(data.frame(inla.smarginal(alpha)),
#                           x >= quant2),
#             fill = "black") +
#   ggtitle("TRI") + 
#   theme_bw()
# 

```

```{r}
data$Prop_dead_pred = res_glm$summary.fitted.values$mean


summary(data$Prop_dead_pred )

hist(data$Prop_dead_pred )

hist( res_glm$summary.fitted.values$mean )

```

```{r}

plot(data$Prop_dead_pred, data$Prop_dead) #, xlim=c(0,1), ylim=c(0,1)
abline(0,1)


```

```{r}

```






